variable "github_runner_app_id" {
  description = <<-EOT
    The GitHub App's own numeric App ID (KandlerLi's
    kandlerli-home-infra-runner App -- Administration: write,
    installed on every repository in var.github_runner_repositories).
    Not itself secret (GitHub shows it on the App's own public
    settings page), but sourced from the same home-infra/github-runner
    AWS Secrets Manager secret as github_runner_app_private_key for
    convenience -- one JSON blob holds both, matching every other
    Secrets Manager group's own shape in this workspace. Passed in by
    the root's own main.tf (secrets.tf) -- not a root TF_VAR itself,
    this is just the module's own input variable.

    Replaced the module's original github_runner_github_token
    (a durable, manually-rotated fine-grained PAT) 2026-09-16: the
    community myoung34/github-runner image (this module's own runner
    image) natively supports GitHub App auth via APP_ID/
    APP_PRIVATE_KEY/APP_LOGIN in place of ACCESS_TOKEN, minting its
    own short-lived registration token internally at container start
    -- removes the manual PAT-rotation chore entirely rather than just
    making it easier.
  EOT
  type        = string
}

variable "github_runner_app_private_key" {
  description = <<-EOT
    The GitHub App's own private key (PEM, the raw multi-line content
    as GitHub's "Generate a private key" button downloads it) --
    genuinely secret, unlike github_runner_app_id above. Used by the
    runner image's own entrypoint to sign a JWT and mint a fresh,
    short-lived installation access token at container start, the
    same underlying mechanism GitHub's own GITHUB_TOKEN uses inside
    Actions workflows.
  EOT
  type        = string
  sensitive   = true
}

variable "github_runner_owner" {
  description = <<-EOT
    The GitHub account every repository in
    var.github_runner_repositories belongs to. Same value as
    home-infra's github_runner_github_owner Ansible default.
  EOT
  type        = string
  default     = "KandlerLi"
}

variable "github_runner_repositories" {
  description = <<-EOT
    One Deployment per entry. Generated from github/repo-infra's own
    config.yml (every repository with `runner: true`) by home-infra's
    scripts/sync_github_runner_repositories.py, into this repo's own
    repositories.auto.tfvars.json -- Terraform auto-loads that file, so
    nothing here references it explicitly. Never hand-edit that file;
    regenerate it with that script instead, the same "one generator, two
    consumers" pattern the VM-based github_runner role's own
    github_runner_github_repositories Ansible variable already uses.
  EOT
  type = list(object({
    id         = string
    repository = string
  }))
}

variable "github_runner_service_accounts" {
  description = <<-EOT
    Map of repository id -> ServiceAccount name, for the (today: one)
    repository whose runner Deployment should mount a real, narrowly-
    scoped in-cluster ServiceAccount token instead of the automount-
    disabled default every other repo's runner Pod gets. Deliberately
    separate from github_runner_repositories/repositories.auto.tfvars.json
    -- that file is fully machine-generated by home-infra's sync
    script and knows nothing about ServiceAccounts, so this stays a
    small, hand-maintained map here instead of a field the generator
    would need to learn about. A repository id with no entry here gets
    null, same as before this variable existed.
  EOT
  type        = map(string)
  default     = {}
}
