variable "github_runner_github_token" {
  description = <<-EOT
    Fine-grained GitHub PAT with Administration: write on every
    repository in var.github_runner_repositories -- the exact same
    value, same scope as home-infra's own github_runner_github_token
    SOPS secret (the VM-based role's own PAT, reused rather than
    duplicated -- see home-infra's ansible/roles/github_runner/README).
    Pass via TF_VAR_github_runner_github_token at apply time.
  EOT
  type        = string
  sensitive   = true
}

variable "github_runner_owner" {
  description = <<-EOT
    The GitHub account every repository in
    var.github_runner_repositories belongs to. Same value as
    home-infra's github_runner_github_owner Ansible default.
  EOT
  type        = string
  default     = "KandlerLi"
}

variable "github_runner_repositories" {
  description = <<-EOT
    One Deployment per entry. Generated from bootstrap/repo-infra's own
    config.yml (every repository with `runner: true`) by home-infra's
    scripts/sync_github_runner_repositories.py, into this repo's own
    repositories.auto.tfvars.json -- Terraform auto-loads that file, so
    nothing here references it explicitly. Never hand-edit that file;
    regenerate it with that script instead, the same "one generator, two
    consumers" pattern the VM-based github_runner role's own
    github_runner_github_repositories Ansible variable already uses.
  EOT
  type = list(object({
    id         = string
    repository = string
  }))
}

variable "github_runner_service_accounts" {
  description = <<-EOT
    Map of repository id -> ServiceAccount name, for the (today: one)
    repository whose runner Deployment should mount a real, narrowly-
    scoped in-cluster ServiceAccount token instead of the automount-
    disabled default every other repo's runner Pod gets. Deliberately
    separate from github_runner_repositories/repositories.auto.tfvars.json
    -- that file is fully machine-generated by home-infra's sync
    script and knows nothing about ServiceAccounts, so this stays a
    small, hand-maintained map here instead of a field the generator
    would need to learn about. A repository id with no entry here gets
    null, same as before this variable existed.
  EOT
  type        = map(string)
  default     = {}
}
