variable "github_runner_app_id" {
  description = <<-EOT
    The GitHub App's own numeric App ID (KandlerLi's
    kandlerli-home-infra-runner App -- Administration: write,
    installed on every repository in var.github_runner_repositories).
    Not itself secret (GitHub shows it on the App's own public
    settings page), but sourced from the same home-infra/github-runner
    AWS Secrets Manager secret as github_runner_app_private_key for
    convenience -- one JSON blob holds both, matching every other
    Secrets Manager group's own shape in this workspace. Passed in by
    the root's own main.tf (secrets.tf) -- not a root TF_VAR itself,
    this is just the module's own input variable.

    Replaced the module's original github_runner_github_token
    (a durable, manually-rotated fine-grained PAT) 2026-09-16: the
    community myoung34/github-runner image (this module's own runner
    image) natively supports GitHub App auth via APP_ID/
    APP_PRIVATE_KEY/APP_LOGIN in place of ACCESS_TOKEN, minting its
    own short-lived registration token internally at container start
    -- removes the manual PAT-rotation chore entirely rather than just
    making it easier.
  EOT
  type        = string
}

variable "github_runner_app_private_key" {
  description = <<-EOT
    The GitHub App's own private key (PEM, the raw multi-line content
    as GitHub's "Generate a private key" button downloads it) --
    genuinely secret, unlike github_runner_app_id above. Used by the
    runner image's own entrypoint to sign a JWT and mint a fresh,
    short-lived installation access token at container start, the
    same underlying mechanism GitHub's own GITHUB_TOKEN uses inside
    Actions workflows.
  EOT
  type        = string
  sensitive   = true
}

variable "github_runner_owner" {
  description = <<-EOT
    The GitHub account every repository in
    var.github_runner_repositories belongs to. Same value as
    home-infra's github_runner_github_owner Ansible default.
  EOT
  type        = string
  default     = "KandlerLi"
}

variable "github_runner_repositories" {
  description = <<-EOT
    One Deployment per entry. Generated from github/repo-infra's own
    config.yml (every repository with `runner: true`) by home-infra's
    scripts/sync_github_runner_repositories.py, into this repo's own
    repositories.auto.tfvars.json -- Terraform auto-loads that file, so
    nothing here references it explicitly. Never hand-edit that file;
    regenerate it with that script instead, the same "one generator, two
    consumers" pattern the VM-based github_runner role's own
    github_runner_github_repositories Ansible variable already uses.
  EOT
  type = list(object({
    id         = string
    repository = string
  }))
}

variable "github_runner_service_accounts" {
  description = <<-EOT
    Map of repository id -> ServiceAccount name, for the (today: one)
    repository whose runner Deployment should mount a real, narrowly-
    scoped in-cluster ServiceAccount token instead of the automount-
    disabled default every other repo's runner Pod gets. Deliberately
    separate from github_runner_repositories/repositories.auto.tfvars.json
    -- that file is fully machine-generated by home-infra's sync
    script and knows nothing about ServiceAccounts, so this stays a
    small, hand-maintained map here instead of a field the generator
    would need to learn about. A repository id with no entry here gets
    null, same as before this variable existed.
  EOT
  type        = map(string)
  default     = {}
}

variable "github_runner_slots_per_repository" {
  description = <<-EOT
    How many runner Deployments (slots) each repository gets. Every
    slot is an independent ephemeral runner that registers under the
    same labels, so GitHub hands concurrent jobs (e.g. a PR check and
    a post-merge apply) to different slots instead of queueing them.
    Each slot has its own docker-data cache on k3s-node-2's disk and
    its own idle requests (~60m CPU/256Mi), so size k3s-node-2 for
    repositories x slots.
  EOT
  type        = number
  default     = 2

  validation {
    condition     = var.github_runner_slots_per_repository >= 1
    error_message = "At least one runner slot per repository is required."
  }
}

variable "github_runner_prune_interval_seconds" {
  description = <<-EOT
    How often each runner Pod's "pruner" sidecar prunes its own dind
    daemon's unused images and build cache. Every slot has its own
    persistent docker-data hostPath on k3s-node-2's disk, which nothing
    else ever cleans.
  EOT
  type        = number
  default     = 3600
}

variable "github_runner_prune_unused_image_age" {
  description = <<-EOT
    Passed to `docker image prune --all --filter until=`: unused images
    older than this are removed. Images used by a running container are
    never removed regardless.
  EOT
  type        = string
  default     = "24h"
}

variable "github_runner_prune_build_cache_keep_storage" {
  description = <<-EOT
    Passed to `docker builder prune --keep-storage`: the most build
    cache each slot's daemon keeps. This is per slot, so total worst
    case is roughly repositories x slots x this value, plus the
    images kept by github_runner_prune_unused_image_age -- size it
    against k3s-node-2's disk (42GB at time of writing).
  EOT
  type        = string
  default     = "2GB"
}
